openapi: 3.0.0
info:
  title: API de Jugadores de Fútbol
  description: API para gestionar jugadores de fútbol.
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /jugadores:
    get:
      summary: Obtener todos los jugadores
      responses:
        '200':
          description: Lista de jugadores
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Jugador'
            application/x-yaml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Jugador'
    post:
      summary: Añadir un nuevo jugador
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JugadorNuevo'
      responses:
        '200':
          description: Jugador añadido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Jugador'
            application/x-yaml:
              schema:
                $ref: '#/components/schemas/Jugador'
    put:
      summary: Reemplazar todos los jugadores
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/JugadorNuevo'
      responses:
        '200':
          description: Jugadores reemplazados
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Jugador'
            application/x-yaml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Jugador'
  /jugadores/{id}:
    patch:
      summary: Actualizar parcialmente un jugador
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JugadorActualizado'
      responses:
        '200':
          description: Jugador actualizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Jugador'
            application/x-yaml:
              schema:
                $ref: '#/components/schemas/Jugador'
    delete:
      summary: Eliminar un jugador por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Jugador eliminado
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
            application/x-yaml:
              schema:
                type: object
                properties:
                  message:
                    type: string

components:
  schemas:
    Jugador:
      type: object
      properties:
        id:
          type: integer
          example: 1
        nombre:
          type: string
          example: Lionel Messi
        posicion:
          type: string
          example: Delantero
        numero:
          type: integer
          example: 10
        equipo:
          type: string
          example: Inter Miami
    JugadorNuevo:
      type: object
      properties:
        nombre:
          type: string
        posicion:
          type: string
        numero:
          type: integer
        equipo:
          type: string
    JugadorActualizado:
      type: object
      properties:
        nombre:
          type: string
        posicion:
          type: string
        numero:
          type: integer
        equipo:
          type: string
